version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - kubectl config view
      - kubectl config set-cluster arn:aws:eks:ap-east-1:375844669971:cluster/PTK-EKS --server=https://A5A58ED4F2599EEA0E75BDD8EBE7169A.sk1.ap-east-1.eks.amazonaws.com
      - kubectl config set-cluster arn:aws:eks:ap-east-1:375844669971:cluster/PTK-EKS --certificate-authority-data=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EUXhPVEEzTXprd05Wb1hEVE14TURReE56QTNNemt3TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkJzClNHZWwwYmc4M1JhTERrbkxBdG1KNXpoSFRaWFFuWmZGb0J2bXR4azRWWVZ4SW00cHBqUllGZU1pWHoyMWhaZDIKaWhPL3VrR0RZTjNJK0k4cGRZODVCODFxeTZ1cGdiUDlnbnlMSGl5R2Rick5IU3RiZ001UnQ2NkE3OGcyaDh6VApRQ2V3bmlqM3JkeXZCQVRTaVFjdGxicmdDajJMWkwwRHpPam4ydEFha3dQV1lPREw0cXdRaHF1ZXRIb0UvUjZWCldBZnhVNmVYUEpya2dFUC9yQko0MjBMR0ZBM1IxazlDQUUxcjhweVRTM0crTTZxZUNtRU1penB5ZHloL0UyOWwKNmNycWV5UjBGTTQwR2poRGhJcXFxOVVnbFhnVml4SHNnYmMxcmhVQ2dOYzc5R3hGb0ZjYlM5cTA4OWdHWk1KMwpCNUdFYktNanFDa21ubmxkaXlrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBZGVMZG9XNGczWlNib0hLaWczMS9MNEIyNnIKNlZvanZOMFk4SWZuM1RpRUZ3cHIzUDM0M1NnWU1wYVUxUGhSMkRtT1pWQmhkVHlzZkNXc05kNWVUOGxGSGJJego3a2lLV1pwT2dNTnRVKzZkVkZDWWw2eXpic0pRZzRlNG0zdjhCanhwazFVUUVIY0tTcGk1SlRvM1FndU4weG5ZCjNicVRCMm1QQlI2dVB5TEdZSjJ3ZWM1U2xvMWlqNVNoU0ppeCtHMEQwdDhRNUNCZFZxcUQxaW9GVGtyQk5tQWcKM1Fxc21yTUFmUnI5U21Wd1JWU0lXZUFxRlA0VTVpUDhQOXBnMExEYlhySmVBbG05WDFDNFJMWlhMMDN5djA5cgpCS25MY0lrVE8yUmxUbnVDdVlXZSt4OHppdUhycURxZjVYenZ0Tm9QZzJxWGhQVnNBWENPYWp2dWwwaz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      - kubectl config set-credentials arn:aws:eks:ap-east-1:375844669971:cluster/PTK-EKS --username=Kinglon --password=&WQ^wk6=Kinglon
      - kubectl config set-context arn:aws:eks:ap-east-1:375844669971:cluster/PTK-EKS --cluster=arn:aws:eks:ap-east-1:375844669971:cluster/PTK-EKS --user=arn:aws:eks:ap-east-1:375844669971:cluster/PTK-EKS
      - kubectl config use-context=arn:aws:eks:ap-east-1:375844669971:cluster/PTK-EKS
      - kubectl config view
      - kubectl get node
      - mvn package
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
#      - kubectl patch deployment myapp-deploy --patch '{spec:{template:{spec:{containers:[{name:myapp,image:$IMAGE_URI}]}}}}' -n default
