version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - kubectl config set-cluster arn:aws:eks:ap-east-1:375844669971:cluster/PTK-EKS --server=https://A5A58ED4F2599EEA0E75BDD8EBE7169A.sk1.ap-east-1.eks.amazonaws.com
      - kubectl config set-cluster arn:aws:eks:ap-east-1:375844669971:cluster/PTK-EKS --insecure-skip-tls-verify=true
      - kubectl get node
      - mvn package
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
#      - kubectl patch deployment myapp-deploy --patch '{spec:{template:{spec:{containers:[{name:myapp,image:$IMAGE_URI}]}}}}' -n default
